name: Building and Testing

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build system
        run: sudo apt-get update && sudo apt-get install -y cmake clang ninja-build

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED=ON -DBUILD_TESTS=ON -DLAUNCH_TESTS=ON .. -G Ninja
          ninja

